### ISSUE TITLE
Heatmap display config could not be saved

### ISSUE THREAD

**Issue by pikewong** [datavoyagerhk/kibana-pivot-table#1]
Hi, there,

In edit mode, we can select different visualization including Heatmap. The heatmap work in the Edit mode. However, when we exit Edit mode, the visualization is revert back to original and could not be saved.

**Comment by vivtony00** [comment]
Issue solved in release v0.1.0.
Install the release would solve the table type saving ploblem.

[https://github.com/datavoyagerhk/kibana-pivot-table/releases/tag/v0.1.0](https://github.com/datavoyagerhk/kibana-pivot-table/releases/tag/v0.1.0)
